/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;
import com.incloud.hcp.domain._framework.IdentifiableHashBuilder;

import javax.persistence.*;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "app_parametria")
//@Audited
//@AuditTable("_audi_APP_PARAMETRIA")
public class AppParametria extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(AppParametria.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String description;
    private String label;
    private String modulo;
    private String status;
    private String value1;
    private String value2;
    private String value3;

    @Override
    public String entityClassName() {
        return AppParametria.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "parametria_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_app_parametria")
    @Id
    @SequenceGenerator(name = "seq_app_parametria", sequenceName = "seq_app_parametria", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public AppParametria id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [description] ------------------------


    @Column(name = "description", length = 512)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public AppParametria description(String description) {
        setDescription(description);
        return this;
    }
    // -- [label] ------------------------


    @Column(name = "label", length = 255)
    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public AppParametria label(String label) {
        setLabel(label);
        return this;
    }
    // -- [modulo] ------------------------


    @Column(name = "modulo", length = 100)
    public String getModulo() {
        return modulo;
    }

    public void setModulo(String modulo) {
        this.modulo = modulo;
    }

    public AppParametria modulo(String modulo) {
        setModulo(modulo);
        return this;
    }
    // -- [status] ------------------------


    @Column(name = "status", length = 1)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public AppParametria status(String status) {
        setStatus(status);
        return this;
    }
    // -- [value1] ------------------------


    @Column(name = "value_1", length = 100)
    public String getValue1() {
        return value1;
    }

    public void setValue1(String value1) {
        this.value1 = value1;
    }

    public AppParametria value1(String value1) {
        setValue1(value1);
        return this;
    }
    // -- [value2] ------------------------


    @Column(name = "value_2", length = 100)
    public String getValue2() {
        return value2;
    }

    public void setValue2(String value2) {
        this.value2 = value2;
    }

    public AppParametria value2(String value2) {
        setValue2(value2);
        return this;
    }
    // -- [value3] ------------------------


    @Column(name = "value_3", length = 100)
    public String getValue3() {
        return value3;
    }

    public void setValue3(String value3) {
        this.value3 = value3;
    }

    public AppParametria value3(String value3) {
        setValue3(value3);
        return this;
    }

    /**
     * Apply the default values.
     */
    public AppParametria withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof AppParametria && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this AppParametria instance.
     * @see Object#toString()
     */

    @Override
    public String toString() {
        return "AppParametria{" +
                "id=" + id +
                ", description='" + description + '\'' +
                ", label='" + label + '\'' +
                ", modulo='" + modulo + '\'' +
                ", status='" + status + '\'' +
                ", value1='" + value1 + '\'' +
                ", value2='" + value2 + '\'' +
                ", value3='" + value3 + '\'' +
                '}';
    }
}
