/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "curso", uniqueConstraints = { @UniqueConstraint(name = "unq_curso", columnNames = { "nombre", "nivel" }) })
//@Audited
//@AuditTable("_audi_CURSO")
public class Curso extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Curso.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String nombre;
    private String nivel;
    private String descripcion;
    private Integer totalHoras;

    @Override
    public String entityClassName() {
        return Curso.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "curso_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_curso")
    @Id
    @SequenceGenerator(name = "seq_curso", sequenceName = "seq_curso", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Curso id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [nombre] ------------------------


    @Column(name = "nombre", nullable = false, length = 200)
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Curso nombre(String nombre) {
        setNombre(nombre);
        return this;
    }
    // -- [nivel] ------------------------


    @Column(name = "nivel", nullable = false, length = 10)
    public String getNivel() {
        return nivel;
    }

    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    public Curso nivel(String nivel) {
        setNivel(nivel);
        return this;
    }
    // -- [descripcion] ------------------------


    @Column(name = "descripcion", nullable = false, length = 255)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Curso descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }
    // -- [totalHoras] ------------------------


    @Column(name = "total_horas", nullable = false, precision = 5)
    public Integer getTotalHoras() {
        return totalHoras;
    }

    public void setTotalHoras(Integer totalHoras) {
        this.totalHoras = totalHoras;
    }

    public Curso totalHoras(Integer totalHoras) {
        setTotalHoras(totalHoras);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Curso withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Curso && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        return Objects.hash(id, nombre, nivel, descripcion, totalHoras, previousHashCode);
    }

    @Override
    public String toString() {
        return "Curso{" +
                "id=" + id +
                ", nombre='" + nombre + '\'' +
                ", nivel='" + nivel + '\'' +
                ", descripcion='" + descripcion + '\'' +
                ", totalHoras=" + totalHoras +
                '}';
    }
}
