/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;
import com.incloud.hcp.domain._framework.IdentifiableHashBuilder;

import javax.persistence.*;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "participante")
//@Audited
//@AuditTable("_audi_PARTICIPANTE")
public class Participante extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Participante.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String nombre;
    private String apellido;
    private String sexo;
    private Integer edad;
    private String profesion;
    private String rol;
    private String direccion;

    @Override
    public String entityClassName() {
        return Participante.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "participante_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_participante")
    @Id
    @SequenceGenerator(name = "seq_participante", sequenceName = "seq_participante", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Participante id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [nombre] ------------------------



    @Column(name = "nombre", nullable = false, length = 50)
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Participante nombre(String nombre) {
        setNombre(nombre);
        return this;
    }

    @Column(name = "direccion", nullable = false, length = 50)
    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public Participante direccion(String direccion) {
        setDireccion(direccion);
        return this;
    }
    // -- [apellido] ------------------------


    @Column(name = "apellido", nullable = false, length = 150)
    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public Participante apellido(String apellido) {
        setApellido(apellido);
        return this;
    }
    // -- [sexo] ------------------------


    @Column(name = "sexo", nullable = false, length = 1)
    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public Participante sexo(String sexo) {
        setSexo(sexo);
        return this;
    }
    // -- [edad] ------------------------


    @Column(name = "edad", nullable = false, precision = 5)
    public Integer getEdad() {
        return edad;
    }

    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    public Participante edad(Integer edad) {
        setEdad(edad);
        return this;
    }
    // -- [profesion] ------------------------


    @Column(name = "profesion", length = 50)
    public String getProfesion() {
        return profesion;
    }

    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }

    public Participante profesion(String profesion) {
        setProfesion(profesion);
        return this;
    }
    // -- [rol] ------------------------


    @Column(name = "rol", nullable = false, length = 1)
    public String getRol() {
        return rol;
    }

    public void setRol(String rol) {
        this.rol = rol;
    }

    public Participante rol(String rol) {
        setRol(rol);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Participante withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Participante && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Participante instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return "Participante{" +
                "id=" + id +
                ", nombre='" + nombre + '\'' +
                ", apellido='" + apellido + '\'' +
                ", sexo='" + sexo + '\'' +
                ", edad=" + edad +
                ", profesion='" + profesion + '\'' +
                ", rol='" + rol + '\'' +
                ", direccion='" + direccion + '\'' +
                '}';
    }
}
